version: '3.5'
services:
  nginx-cryp:
    container_name: nginx-cryp
    build:
      context: docker/nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./:/var/www/html/cryptopro
      - ./docker/nginx/logs:/data/www/logs/cryptopro
    depends_on:
      - php-fpm-cryp
    networks:
      cryp_net:
        aliases:
          - ${APP_URL}
  php-fpm-cryp:
    container_name: php-fpm-cryp
    build:
      context: docker
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/cryptopro
    depends_on:
      - db-cryp
    networks:
      - cryp_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db-cryp:
    container_name: db-cryp
    image: 'postgres:15'
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./docker/postgresql/database:/var/lib/postgresql/data
    networks:
      - cryp_net
networks:
  cryp_net:
    ipam:
      driver: default
      config:
        - subnet: ${NETWORK_CRYP_SUBNET}
